using UnityEditor;
using UnityEngine;

namespace SuyuRun.Editor
{
    // Every pixel-art sprite generated by the Tools/gen_costa_*.py scripts lands in one of these
    // folders. Import them as crisp sprites: Point filtering (no smoothing between the authored
    // pixels), Repeat wrap (the sea layers scroll their UVs to animate) and no compression (they
    // are tiny, compression artifacts would show at this scale).
    public sealed class CostaPixelArtImport : AssetPostprocessor
    {
        static readonly string[] Folders = { "Assets/SuyuRun/Art/Resources/Sea/", "Assets/SuyuRun/Art/Resources/Boats/", "Assets/SuyuRun/Art/Resources/Swimmer/", "Assets/SuyuRun/Art/Resources/Sky/", "Assets/SuyuRun/Art/Resources/Ground/" };
        void OnPreprocessTexture()
        {
            var path = assetPath.Replace('\\', '/');
            bool inPixelArtFolder = false;
            foreach (var folder in Folders) if (path.Contains(folder)) { inPixelArtFolder = true; break; }
            if (!inPixelArtFolder) return;
            var importer = (TextureImporter)assetImporter;
            importer.textureType = TextureImporterType.Sprite;
            importer.spriteImportMode = SpriteImportMode.Single;
            importer.spritePixelsPerUnit = 64;
            importer.alphaIsTransparency = true;
            importer.mipmapEnabled = false;
            importer.wrapMode = TextureWrapMode.Repeat;
            importer.filterMode = FilterMode.Point;
            importer.textureCompression = TextureImporterCompression.Uncompressed;
            var settings = importer.GetDefaultPlatformTextureSettings();
            settings.textureCompression = TextureImporterCompression.Uncompressed;
            importer.SetPlatformTextureSettings(settings);
        }
    }
}
